import { normalizeSymptomName } from '../../utils/sanitizers.js';

export const DEFAULT_SYMPTOM_WEIGHT = 1;

export const SYMPTOM_WEIGHTS = Object.freeze({
  'chest pain': 1.9,
  'shortness of breath': 1.8,
  'difficulty breathing': 1.8,
  'difficulty speaking': 1.6,
  'breathing fast': 1.5,
  'loss of consciousness': 2,
  seizures: 1.9,
  paralysis: 2,
  'severe abdominal pain': 1.8,
  'abdominal pain': 1.2,
  'coughing blood': 2,
  'blood in urine': 1.8,
  'blood in stool': 1.8,
  jaundice: 1.6,
  'high fever': 1.5,
  fever: 1.4,
  palpitations: 1.5,
  'rapid heart rate': 1.5,
  dizziness: 1.2,
  weakness: 1.1,
  fatigue: 1,
  cough: 1.1,
  'dry cough': 1.1,
  'productive cough': 1.2,
  'sore throat': 0.9,
  'throat swelling': 1.7,
  'throat feels tight': 1.7,
  'chest tightness': 1.5,
  rash: 1.1,
  'skin rash': 1.2,
  vomiting: 1.3,
  diarrhea: 1.2,
  nausea: 1.1,
  headache: 0.9,
  'sudden severe headache': 1.9,
  depression: 0.7,
  anxiety: 0.8,
  'anxiety and nervousness': 0.9,
  insomnia: 0.7,
  'swollen lymph nodes': 1.4,
  'weight loss': 1.4,
  'night sweats': 1.3,
  chills: 1.2,
  'joint pain': 1.1,
  'muscle pain': 1,
  'runny nose': 0.6,
  'stuffy nose': 0.6,
  sneezing: 0.5,
  itching: 0.7,
  'loss of taste': 1,
  'loss of smell': 1,
});

export function getSymptomWeight(symptomName) {
  return SYMPTOM_WEIGHTS[normalizeSymptomName(symptomName)] ?? DEFAULT_SYMPTOM_WEIGHT;
}
